### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by q2dg** [security-companion/w3af#724]
Last commit was a year ago...
Thanks!

**Comment by codders** [comment]
Eh. I mean, not quite abandoned, but there isn't really enough interest
from users to keep it alive.

I'm available as a maintainer and will merge patches and fixes, but it
would require a larger group of active committers to bring the project back
to life.

Osqui LittleRiver ***@***.***> schrieb am Mo., 23. Dez. 2024,
23:54:

**Comment by q2dg** [comment]
Ok, thanks a lot for your response
If you don't mind, i'll close this issue, then.
